services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: anime
      POSTGRES_PASSWORD: anime
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: